spring:
  application:
    name: cow_mvc_practice
  jpa:
    hibernate:
      ddl-auto: create

  docker:
    compose:
      file: compose.yaml
      enabled: true
      lifecycle-management: start_and_stop
      start:
        command: up
      stop:
        command: down
        timeout: 1m