spring:
  application:
    name: cow_mvc_practice
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true

  docker:
    compose:
      file: compose.yaml
      enabled: true
      lifecycle-management: START_ONLY
      start:
        command: up
      stop:
        command: down
        timeout: 1m

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace